"""Phase 32 - Audit Signing Policy.

Defines deterministic local HMAC-SHA256 signing for Phase 32 evidence.
Stdlib only. No real production secrets. Test-only.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import secrets
import time
import uuid
from pathlib import Path
from typing import Any


_PHASE = "phase32.signing_policy.v1"


SUPPORTED_ALGORITHMS = ("HMAC-SHA256",)


_FORBIDDEN_KEY_LABELS = (
    "prod", "production", "live", "real", "kms", "cloud",
    "external",
)


def get_audit_signing_policy() -> dict[str, Any]:
    return {
        "version": _PHASE,
        "supported_algorithms": list(SUPPORTED_ALGORITHMS),
        "test_only_required": True,
        "json_canonicalization": "json.dumps(sort_keys=True,"
                                   "default=str,ensure_ascii=False)",
        "key_material_size_bytes": 32,
        "notes": [
            "Phase 32 permits only HMAC-SHA256 test signing.",
            "Test keys generated by stdlib secrets module only.",
            "No production secrets committed.",
            "No external KMS / OS keychain / cloud signing.",
        ],
    }


def get_supported_signature_algorithms() -> list[str]:
    return list(SUPPORTED_ALGORITHMS)


def canonicalize_for_signing(obj: Any) -> str:
    """Deterministic JSON serialization for signing."""
    return json.dumps(obj, sort_keys=True, default=str,
                       ensure_ascii=False)


def create_test_signing_key(
    label: str = "phase32_test_key",
) -> dict[str, Any]:
    label_l = str(label or "").lower()
    if any(bad in label_l for bad in _FORBIDDEN_KEY_LABELS):
        raise ValueError(
            f"forbidden_label:{label} (Phase 32 is test-only)")
    return {
        "key_id": f"k_{int(time.time())}_{uuid.uuid4().hex[:10]}",
        "label": str(label or "phase32_test_key"),
        "algorithm": "HMAC-SHA256",
        "test_only": True,
        "material_hex": secrets.token_hex(32),
        "created_at": time.time(),
        "phase": _PHASE,
        "notes": "phase32 test signing key; do not commit to git",
    }


def validate_signing_key_descriptor(
    key_descriptor: Any,
) -> dict[str, Any]:
    reasons: list[str] = []
    if not isinstance(key_descriptor, dict):
        return {"ok": False, "reasons": ["key_descriptor_not_dict"]}
    for f in ("key_id", "label", "algorithm", "test_only",
              "material_hex", "created_at", "phase"):
        if f not in key_descriptor:
            reasons.append(f"missing_field:{f}")
    alg = str(key_descriptor.get("algorithm") or "")
    if alg not in SUPPORTED_ALGORITHMS:
        reasons.append(f"unsupported_algorithm:{alg}")
    if key_descriptor.get("test_only") is not True:
        reasons.append("test_only_must_be_true")
    label_l = str(key_descriptor.get("label") or "").lower()
    if any(bad in label_l for bad in _FORBIDDEN_KEY_LABELS):
        reasons.append(f"forbidden_label:{key_descriptor.get('label')}")
    mat = key_descriptor.get("material_hex") or ""
    if not isinstance(mat, str) or len(mat) < 32:
        reasons.append("material_hex_too_short")
    return {"ok": not reasons, "reasons": reasons}


def create_signature_metadata(
    algorithm: str = "HMAC-SHA256",
    key_id: str = "test",
) -> dict[str, Any]:
    if algorithm not in SUPPORTED_ALGORITHMS:
        algorithm = "HMAC-SHA256"
    return {
        "algorithm": algorithm,
        "key_id": str(key_id or "test"),
        "signed_at": time.time(),
        "phase": _PHASE,
    }


def validate_signature_metadata(metadata: Any) -> dict[str, Any]:
    reasons: list[str] = []
    if not isinstance(metadata, dict):
        return {"ok": False, "reasons": ["metadata_not_dict"]}
    for f in ("algorithm", "key_id", "signed_at", "phase"):
        if f not in metadata:
            reasons.append(f"missing_field:{f}")
    alg = str(metadata.get("algorithm") or "")
    if alg not in SUPPORTED_ALGORITHMS:
        reasons.append(f"unsupported_algorithm:{alg}")
    return {"ok": not reasons, "reasons": reasons}


def sign_payload(payload: Any, key_descriptor: dict[str, Any]) -> str:
    """Internal helper: HMAC-SHA256 hex digest over canonical JSON."""
    mat = bytes.fromhex(str(key_descriptor.get("material_hex") or ""))
    msg = canonicalize_for_signing(payload).encode("utf-8")
    return hmac.new(mat, msg, hashlib.sha256).hexdigest()


def write_audit_signing_policy_report(
    report: dict[str, Any],
    output_path: str,
) -> str:
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    body = dict(report)
    body["written_at"] = time.time()
    p.write_text(json.dumps(body, ensure_ascii=False, indent=2,
                            default=str), encoding="utf-8")
    return str(p)


__all__ = [
    "SUPPORTED_ALGORITHMS",
    "get_audit_signing_policy",
    "get_supported_signature_algorithms",
    "canonicalize_for_signing",
    "create_test_signing_key",
    "validate_signing_key_descriptor",
    "create_signature_metadata",
    "validate_signature_metadata",
    "sign_payload",
    "write_audit_signing_policy_report",
]
