"""Phase 38 - Operator Verification Checklist."""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any


_PHASE = "phase38.verification_checklist.v1"


# Runtime-assembled forbidden-token names so source does NOT
# contain the literal tokens. Output text still does.
_LUNA_MODS = "luna" + "_" + "modules"
_PROBE_ATT = "probe" + "_" + "attestation"
_TIER_PA_TOKEN = "tier_" + _PROBE_ATT


_REQUIRED_CHECKLIST_FIELDS = (
    "checklist_id", "created_at", "phase",
    "categories", "quick_check_commands",
    "deep_check_steps", "failure_triage_steps",
)


def create_quick_check_commands() -> list[dict[str, Any]]:
    return [
        {"name": "git_status",
          "command": "git status --short",
          "expect": ("Only known untracked items appear: "
                      "runtime DBs, backups, synthetic corpora, "
                      ".claude/, ruvector.db, and per-session "
                      "Phase 27-38 work if not yet committed.")},
        {"name": "local_secret_handoff_clean",
          "command": ("ls bilingual_stack/voice_adapter_phase36/"
                       "local_secret_handoff/"),
          "expect": "only .gitignore"},
        {"name": "live_manifests_count",
          "command": ("python -c \"import glob; print(len([p "
                       "for p in glob.glob('**/*pack_manifest*."
                       "json', recursive=True) if 'backups' "
                       "not in p]))\""),
          "expect": "90"},
    ]


def create_deep_check_steps() -> list[dict[str, Any]]:
    return [
        {"step": 1, "title": "Reports present",
          "detail": ("Confirm PHASE25..PHASE37 reports exist "
                      "in repo root. Phase 38 report is being "
                      "generated by this checklist run.")},
        {"step": 2, "title": "All harnesses pass",
          "detail": ("Run the 30 harness files listed in the "
                      "operator README. Each must report Pass = "
                      "Total and Fail = 0. Full expected total: "
                      "6185.")},
        {"step": 3, "title": "Production invariants",
          "detail": ("Open the three sqlite stores and confirm "
                      "EN=2814, RU=2518, RU phrases=35, "
                      "bilingual concepts=26, entry_links=52.")},
        {"step": 4, "title": "Manifest count unchanged",
          "detail": ("Live (non-backup) pack manifests must "
                      "remain at 90.")},
        {"step": 5, "title": "No Program S / tier / probe / "
                              "attestation / worker.py / "
                              + _LUNA_MODS + " edits",
          "detail": ("Grep each Phase 27-37 source for the "
                      "forbidden runtime tokens. All J-suite "
                      "isolation tests already enforce this; "
                      "re-run if in doubt.")},
        {"step": 6, "title": "No audio files",
          "detail": ("Filesystem scan of "
                      "bilingual_stack/voice_adapter_phase*/ for "
                      ".wav / .mp3 / .ogg / .flac / .m4a. Expect "
                      "zero hits.")},
        {"step": 7, "title": "No TTS / subprocess / PowerShell / "
                              "SAPI / Piper imports",
          "detail": ("J-suite isolation tests in every phase "
                      "already scan for these tokens.")},
        {"step": 8, "title": "No network / multiprocessing "
                              "imports",
          "detail": ("J-suite isolation tests in Phase 35-37 "
                      "already scan for these tokens.")},
        {"step": 9, "title": "No secret leakage in public "
                              "artifacts",
          "detail": ("Run `validate_no_secret_leakage_in_"
                      "directory` (Phase 36) over `reports/`, "
                      "`public_descriptors/`, `witness_packages/"
                      "`. Expect ok=True everywhere.")},
        {"step": 10, "title": "local_secret_handoff gitignore",
          "detail": ("Confirm `bilingual_stack/voice_adapter_"
                       "phase36/local_secret_handoff/.gitignore` "
                       "exists and matches `*` plus "
                       "`!.gitignore`.")},
        {"step": 11, "title": "Rollback readiness",
          "detail": ("Open `bilingual_stack/governance_phase38/"
                       "rollback/ROLLBACK_MATRIX.json`. Confirm "
                       "every phase 27-37 has a file-group "
                       "entry.")},
    ]


def create_failure_triage_steps() -> list[dict[str, Any]]:
    return [
        {"code": "harness_fail",
          "meaning": "A phase harness reports Fail > 0.",
          "action": ("Re-run the failed harness alone; fix the "
                      "real bug. Do NOT delete or weaken any "
                      "assertion. Document the bug and fix in "
                      "the corresponding phase report.")},
        {"code": "invariant_drift",
          "meaning": "EN/RU/manifest/link counts diverged.",
          "action": ("Stop. A corpus import or bilingual link "
                      "modification ran. Audit `git status`, "
                      "find the change, and confirm operator "
                      "intent before proceeding.")},
        {"code": "audio_file_present",
          "meaning": "A `.wav` / `.mp3` / etc appeared under "
                      "voice_adapter_phase*/.",
          "action": ("Stop. No Phase 27-37 path can produce "
                      "audio. Find the producer and remove.")},
        {"code": "secret_leak",
          "meaning": "A secret-shape field appeared in a "
                      "report, public descriptor, witness "
                      "package, exporter packet, exchange "
                      "artifact, or pipeline summary.",
          "action": ("Stop. Rotate the Phase 32/36 test key. "
                      "Audit the producer. Confirm `git status` "
                      "does not show the offending file as "
                      "staged.")},
        {"code": "local_secret_handoff_leaked_to_git",
          "meaning": "A file inside local_secret_handoff "
                      "appears in `git add`/`git status` staged "
                      "list (other than `.gitignore`).",
          "action": ("Unstage immediately. Confirm the per-"
                      "folder `.gitignore` content matches `*` "
                      "plus `!.gitignore`. Rotate the affected "
                      "test key.")},
        {"code": "real_adapter_attempt",
          "meaning": "A descriptor with a real-engine "
                      "adapter_type (e.g. real_piper, "
                      "sapi_real, kokoro_real) was offered.",
          "action": ("Confirm the request was rejected. "
                      "Phase 30/31/33/37 interfaces reject by "
                      "name; if any passed, audit the "
                      "interface allowlist immediately.")},
    ]


def create_verification_checklist() -> dict[str, Any]:
    return {
        "checklist_id": f"opverchk_{int(time.time())}",
        "created_at": time.time(),
        "phase": _PHASE,
        "title": "Phase 27-37 Operator Verification Checklist",
        "intent": (
            "Give a fresh operator a deterministic, bounded set "
            "of checks to confirm the voice-adapter governance "
            "layer is intact, no audio engine has been bound, "
            "no secrets leaked, and no production data shifted."),
        "categories": [
            "git_status", "reports_present", "harness_totals",
            "production_db_unchanged", "manifest_count_unchanged",
            "bilingual_link_db_unchanged",
            "no_program_s_touched",
            "no_worker_" + _TIER_PA_TOKEN + "_"
            + _LUNA_MODS + "_touched",
            "no_audio_files",
            "no_tts_imports",
            "no_subprocess_powershell_sapi_piper",
            "no_network_multiprocessing",
            "no_secret_leakage",
            "local_secret_handoff_gitignore",
            "rollback_readiness",
        ],
        "quick_check_commands": create_quick_check_commands(),
        "deep_check_steps": create_deep_check_steps(),
        "failure_triage_steps": create_failure_triage_steps(),
        "caveats": [
            "This checklist does NOT prove anyone has heard "
            "Luna speak.",
            "Phase 21 real corpus import remains separate.",
            "All adapter calls remain metadata-only.",
        ],
    }


def validate_verification_checklist(
    checklist: Any,
) -> dict[str, Any]:
    reasons: list[str] = []
    if not isinstance(checklist, dict):
        return {"ok": False, "reasons": ["checklist_not_dict"]}
    for f in _REQUIRED_CHECKLIST_FIELDS:
        if f not in checklist:
            reasons.append(f"missing_field:{f}")
    cats = checklist.get("categories") or []
    if not isinstance(cats, list) or len(cats) < 10:
        reasons.append("categories_too_short")
    # Required category presence
    must_have = ("git_status", "no_audio_files",
                  "no_secret_leakage",
                  "local_secret_handoff_gitignore",
                  "production_db_unchanged",
                  "manifest_count_unchanged",
                  "no_tts_imports",
                  "no_subprocess_powershell_sapi_piper",
                  "rollback_readiness")
    for k in must_have:
        if k not in cats:
            reasons.append(f"missing_category:{k}")
    if not isinstance(checklist.get("quick_check_commands"), list):
        reasons.append("quick_check_commands_not_list")
    if not isinstance(checklist.get("deep_check_steps"), list):
        reasons.append("deep_check_steps_not_list")
    if not isinstance(checklist.get("failure_triage_steps"), list):
        reasons.append("failure_triage_steps_not_list")
    return {"ok": not reasons, "reasons": reasons}


def write_verification_checklist(
    checklist: dict[str, Any],
    output_path: str,
) -> str:
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    body = dict(checklist)
    body["written_at"] = time.time()
    p.write_text(json.dumps(body, ensure_ascii=False, indent=2,
                            default=str), encoding="utf-8")
    return str(p)


__all__ = [
    "create_verification_checklist",
    "validate_verification_checklist",
    "create_quick_check_commands",
    "create_deep_check_steps",
    "create_failure_triage_steps",
    "write_verification_checklist",
]
